### PR TITLE
Use the Configured Defaults when Outside the EU

### PR DESCRIPTION
**Pull request by dhurlburtusa**

### CODE REVIEW

**Comment by dhurlburtusa** [comment]
[Cookie Kit: ignores checked by default](https://trello.com/c/FBN4WVSG/4352-cookie-kit-ignores-checked-by-default)

**Review by Bilal-S — APPROVED** [review]
Seems pretty simple. I will merge and run the tests.

**Comment by Bilal-S** [comment]
@dhurlburtusa 
I see that we did a PR against master here. 
I will test it but, we will need to sync dev as well.

**Comment by Bilal-S** [comment]
@dhurlburtusa 
We are nearly there.
We are now using the directives in `checkByDefaultTypes` however all the time and only checking what is marked there. 
However when we are inside the `EU` or user is from `EU` country  this should be ignored. 
Only check application and leave the others blank.

For example:

```
<script type="text/javascript">
  XcooBee.kit.initialize({
    checkByDefaultTypes: ["application","advertising"],
    cookieHandler: "myChFunction",    
    position: "right_bottom",
    privacyUrl: "#privacy",
    requestDataTypes: ["statistics","advertising"],      
    termsUrl: "#terms",
    textMessage: "Welcome to our cafe site. We use cookies and fingerprinting techniques to serve you better. Please let us know if this is OK. Click the link under each section to learn more. If you need to exclude yourself from information collection and sharing, you can check the Do-Not-Sell option at any time.",
    testMode: true,
    displayFingerprint:false,
    displayDoNotSell: false,
    displayOnlyForEU: false,
    theme: "overlay"
  });
```

Has `displayOnlyForEU` for set to `false` which indicates EU treatment. We default to application cookies checked and everything else unchecked.

**Pull request merged**
